### ISSUE TITLE
Text overlapping (not responsive)

### ISSUE THREAD

**Issue by kartikaysaxena** [camicroscope/caMicroscope#584]
**Describe the bug**
On the Workbench Page, the workbench and the options markup wraps up on one another.

**To Reproduce**
1. Go to 'Workbench page'
2. Make the resolution low
3. See how Workbench and options gets wrapped up

**Screenshots**
How it shows
<img width="1440" alt="Screenshot 2023-03-06 at 9 18 35 AM" src="https://user-images.githubusercontent.com/120778728/223017616-b446c15c-6bd7-4b79-a6f7-f160c6fda39a.png">
How it will show after fixing
<img width="1440" alt="Screenshot 2023-03-06 at 9 18 30 AM" src="https://user-images.githubusercontent.com/120778728/223017653-bac9b010-b70a-437e-b2ed-126f90d49673.png">

**Smartphone (please complete the following information):**
 - Device: iPhone8

**Comment by AbhishekCS3459** [comment]
@kartikaysaxena assign me this issue I will change the media queries for the same so that it will get resolved.

**Comment by kartikaysaxena** [comment]
@AbhishekCS3459 I have made changes and raised a PR. You can look for other issues

**Comment by AdityaDey-80** [comment]
### I WANT TO WORK ON THIS ISSUE

- Why does text overlap occur?

This is happening because the default is width: auto . Which means the boxes would expand based on its content. However, when we slap a fixed width, we restrict it from growing. And with no where to go, the text bleeds into its sibling box.

- Solution to overlapping text

We can easily fix this by changing our white-space to normal.

.container {
  display: flex;
}

.boxes {
  width: 100px;
  white-space: normal; // 
}
👈
Thanks/regards---
### ADITYA DEY
