### ISSUE TITLE
Separate Magnifier

### ISSUE THREAD

**Issue by birm** [camicroscope/caMicroscope#69]
GOAL: A way to see high detail in a region without changing the main view.

Possible Implementation: Open a separate window or div and keep its x and y position matched with the crosshair/pointer position.

**Comment by birm** [comment]
working in packages-1 branch

**Comment by sharmaashish** [comment]
An example of what I have in mind.  https://github.com/picturae/OpenSeadragonMagnifier
I think it's worth looking at this, and maybe extending it so that the magnifier moves with the mouse. Maybe even fork the repo and the make the changes on that fork.

The one requirement that is somewhat unique is that the magnifier must display annotations, which in turn might lead us to a separate development.
